# Generated by Django 3.2.7 on 2021-10-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_reader_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CUser',
        ),
    ]
