# Generated by Django 3.2.7 on 2021-10-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_delete_cuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
