# Generated by Django 3.2.7 on 2021-10-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='name',
        ),
        migrations.AlterField(
            model_name='reader',
            name='position',
            field=models.CharField(choices=[('Author', 'Author'), ('Reader', 'Reader')], default='Reader', max_length=10),
        ),
    ]
