# Generated by Django 3.2.7 on 2021-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20211015_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='position',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Publisher', 'Publisher')], default='Reader', max_length=10),
        ),
    ]
