# Generated by Django 3.2.7 on 2021-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_reader_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='position',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Publisher', 'Publisher'), ('Author', 'Author')], default='Reader', max_length=10),
        ),
    ]
