# Generated by Django 3.2.7 on 2021-10-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='feedback',
        ),
    ]
